@startuml 标题

title 
    __Simple__ **communication** example 
    on <i>several</i> lines and using <color:red>html</color>
    This is hosted by <img:myicon.jpg>
end title

Alice -> Bob : 认证请求
Bob -> Alice : 认证响应
@enduml